server:
  port: 8008
spring:
  application:
    name: mq
  activemq:
    pool:
      enabled=true:  #true表示使用连接池；false时，每发送一条数据创建一个连
      max-connections: 10 #连接池最大连接数
      idle-timeout: 30000 #空闲的连接过期时间，默认为30秒
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
